config/routes.rb
WeddingSite::Application.routes.draw do
  
  
  authenticated :user do
    root to: 'home#authenticated', as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks",
    invitations: 'users/invitations'
  }

  resources :users do
    collection do
    post 'batch_invite'
    end
  end

  resources :charges, :messages, :hgh
  get "home/index"
  

  

end

app/views/layouts/_add_user.html.erb
<div id="add-user-field" style="display:none;">
<section class="section" id="section4" >
          <div class="container-fluid">
            <div class="row-fluid title">
              <div class="span3">
                <h2>Add User</h2>
              </div><!-- /span3 -->
            </div><!-- /row-fluid -->
            <div class="row-fluid content faq">
              <h5 style="color: #F1F1F1;">Add a single user</h5>
                    <%= simple_form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
                      <%= devise_error_messages! %>
                    <% resource.class.invite_key_fields.each do |field| -%>
                      <%= f.input field, label_html: {style: 'color: #F1F1F1;'} %>
                    <% end -%>
                    <%= f.button :submit, 'Add User', :class => 'btn-inverse-faq' %>
                    <% end %>
                  </br>
                  
                  <h5 style="color: #F1F1F1;">Add multiple users</h5>
                    <%= simple_form_for resource, :as => resource_name, :url => batch_invite_users_path(resource_name), :html => {:method => :post} do |f| %>
                      <%= devise_error_messages! %>
                      <%= text_area_tag :user_emails %>
                    </br>
                    <%= f.button :submit, 'Batch Invite', :class => 'btn-inverse-faq' %>
                    <% end %>
                  
            </div><!-- /row-fluid -->
          </div><!-- /container-fluid -->
</section>
</div>

app/views/layouts/_edit_account.html.erb
<div id="edit-field" style="display:none;">
<section class="section" id="section4 edit-account" >
          <div class="container-fluid">
            <div class="row-fluid title">
              <div class="span3">
                <h2>Edit Account</h2>
              </div><!-- /span3 -->
            </div><!-- /row-fluid -->
            <div class="row-fluid content">
              <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put, :class => 'form-vertical' }) do |f| %>
                <%= f.input :first_name, :autofocus => true, :input_html => { :value => current_user.first_name } %>
                <%= f.input :last_name, :input_html => { :value => current_user.last_name } %>
                <%= f.input :email, :required => true, :input_html => { :value => current_user.email } %>
                <% if current_user.password_required? %>
                  <%= f.input :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false %>
                  <%= f.input :password_confirmation, :required => false %>
                  <%= f.input :current_password, :hint => "we need your current password to confirm your changes", :required => true %>
                <% end %>
                </br>
                <h5>Change RSVP</h5>           
                <div class="form-group">
                    <div class="col-lg-10">
                      <div class="btn switch switch-three">
                          <input id="rsvp_confirmation_unsure-edit" name="user[rsvp_confirmation]" value="2" type="radio" checked="">
                          <label for="rsvp_confirmation_unsure-edit" onclick="" class="label-rsvp">Undecided</label>

                          <input id="rsvp_confirmation_attending-edit" name="user[rsvp_confirmation]" value="1" type="radio">
                          <label for="rsvp_confirmation_attending-edit" onclick="" class="label-rsvp">Attending</label>

                          <input id="rsvp_confirmation_not_attending-edit" name="user[rsvp_confirmation]" value="0" type="radio">
                          <label for="rsvp_confirmation_not_attending-edit" onclick="" class="label-rsvp">Not Attending</label>

                        <span class="slide-button btn btn-success"></span>
                      </div>
                      </br>
                        <div class="btn switch switch-five" id="number_attending-edit" style="display:none;">
                          <input id="rsvp_count_zero-edit" name="user[rsvp_count]" value="0" type="radio" checked"">
                          <label for="rsvp_count_zero-edit" onclick="" class="label-rsvp"><i class="fa fa-times"></i></label>

                          <input id="rsvp_count_one-edit" name="user[rsvp_count]" value="1" type="radio">
                          <label for="rsvp_count_one-edit" onclick="" class="label-rsvp"><i class="icon-male"></i></label>

                          <input id="rsvp_count_two-edit" name="user[rsvp_count]" value="2" type="radio">
                          <label for="rsvp_count_two-edit" onclick="" class="label-rsvp"><i class="icon-male"></i><i class="icon-female"></i></label>

                          <input id="rsvp_count_three-edit" name="user[rsvp_count]" value="3" type="radio">
                          <label for="rsvp_count_three-edit" onclick="" class="label-rsvp"><i class="icon-male"></i><i class="icon-female"></i><i class="icon-male"></i></label>

                          <input id="rsvp_count_four-edit" name="user[rsvp_count]" value="4" type="radio">
                          <label for="rsvp_count_four-edit" onclick="" class="label-rsvp"><i class="icon-male"></i><i class="icon-female"></i><i class="icon-male"></i><i class="icon-female"></i></label>

                        <span class="slide-button btn btn-success"></span>
                      </div>
                    </div>
                  </div>
                  <p id="small-text" style="text-align:center">* Per your addressed invitation, please indicate the number of guests that will be attending by December 21<sup style="font-size: 5pt;">st</sup><p>
                <%= f.button :submit, 'Update', :class => 'btn-inverse' %>
              <% end %>
            </div>
          </div>
</section>
</div>

app/views/layouts/_faq.html.erb
<div id="faq-field" style="display:none;" data-section"10">
<section class="section" id="section4" >
          <div class="container-fluid">
            <div class="row-fluid title">
              <div class="span3">
                <h2>FAQ</h2>
              </div><!-- /span3 -->
            </div><!-- /row-fluid -->
            <div class="row-fluid content faq">
              <div>
                <button class="btn-inverse-no-data" id="password-reset" href="#password-reset-id">Forgot Your Password?</button>
                <button class="btn-inverse-no-data" id="invite-request" href="#invite-request-id">Request an Invitation</button>
              </div>
              </br>
                <div id="password-reset-id" class="simple-form" style="display:none;">
                  <%= simple_form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => {:method => :post , :class => 'form-vertical' }) do |f| %>
                  <%= f.input :email, :required => true, :autofocus => true, label_html: {style: 'color: #F1F1F1;'} %>
                  <%= f.button :submit, 'Reset password info', :class => 'btn-inverse-faq' %>
                <% end %>                   
              </div>
              <div id="invite-request-id" class="simple-form" style="display:none;">
                <%= simple_form_for(message, :as => message_name, :html => {:class => 'form-vertical' }) do |f| %>
                <% if @message.errors.any? %>
                  <div class="error_messages">
                    <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
                    <ul>
                    <% @message.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                  <%= f.input :name, label_html: {style: 'color: #F1F1F1;'} %><br />
                  <%= f.input :email, label_html: {style: 'color: #F1F1F1;'} %><br />
                  <%= f.button :submit, 'Request invitation ', :class => 'btn-inverse-faq' %>
              <% end %>
            </div>
            </div><!-- /row-fluid -->
          </div><!-- /container-fluid -->
</section>
</div>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-44399206-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert-custom alert-<%= name == :notice ? "success" : name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<head>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
</head>

<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
    <li><%= link_to 'Login', new_user_session_path %></li>
  <% end %>
  <% if user_signed_in? %>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <% if current_user.has_role? :admin %>
      <li><%= link_to 'Admin', users_path %></li>
    <% end %>
  <% else %>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <li><%= link_to '<i class="icon-facebook-sign"></i> Sign in with Facebook'.html_safe, user_omniauth_authorize_path(:facebook) %></li>
  <% end %>
</ul>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
      <a class="btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
        <!-- <div id="logo"> <a href="/"><img src="img/logo.svg" alt="logo" /></a> </div> -->
        <nav id="nav" class="navigation" role="navigation">
          <ul class="unstyled">
            <li id="home"><a href="http://www.sooter-cink-wedding.com"><i class="icon-home"></i><span>Home</span></a></li>
          </ul>
        </nav><!-- /nav -->        
</div>

app/views/layouts/_signin.html.erb
  <div class="top">
    <h2>Sign In</h2>
  </div>
  <div class="bottom">

<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
  <%= f.input :email, :autofocus => true %>
  <%= f.input :password %>
  <%= f.input :remember_me, :as => :boolean, :wrapper => :inline_checkbox if devise_mapping.rememberable? %>
  <%= f.button :submit, "Sign in", :class => 'btn-primary' %>
<% end %>
  </div>

app/views/layouts/_signup.html.erb
  <div class="top">
    <h2>Sign Up</h2>
  </div>
  <div class="bottom">

<%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>

  <%= f.input :first_name, :autofocus => true %>
  <%= f.input :last_name %>
  <%= f.input :email, :required => true %>
  <%= f.input :password, :required => true %>
  <%= f.input :password_confirmation, :required => true %>
  <%= f.input :rsvp_confirmation, :as => :hidden, :input_html => { :value => "2" } %>
  <%= f.button :submit, 'Sign up', :class => 'btn-primary' %>
<% end %>
  </div>

app/views/layouts/_users.html.erb
<body>
  <div id="wrapper">
    <div id="container">
<section class="section" id="section4 edit-account" >
          <div class="container-fluid">
            <div class="row-fluid title">
              <div class="span3">
                <h2>Admin</h2>
              </div><!-- /span3 -->
              <div class="span9 hidden-phone">  
                <hr>
              </div><!-- /span9 -->
            </div><!-- /row-fluid -->
            <table class="table table-condensed">
              <thead>
                <tr>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Registered</th>
                  <th>Role</th>
                  <th>RSVP</th>
                  <th>RSVP</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.full_name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.created_at.to_date %></td>
                  <td><%= user.roles.join(', ').titleize unless user.roles.first.nil? %></td>
                  <td><%= user.rsvp_count %></td>
                  <td>
                    <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini btn-primary" type="button">Change role</a>
                    <%= render user %>
                  </td>
                  <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini btn-danger') unless user == current_user %></td>
                </tr>
              <% end %>
              </tbody>
          </table>
</section>
</div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <LINK REL="SHORTCUT ICON"
       HREF="/assets/logo.ico">
    <title>Sooter-Cink Wedding</title>
    <meta name="description" content="Custom wedding website for Sooter-Cink Wedding">
    <meta name="author" content="Brad Cink">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=9; IE=8;">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <link rel="stylesheet" href="http://getbootstrap.com/2.3.2/assets/js/google-code-prettify/prettify.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="http://bdmdesign.github.io/bootstrap-switch/static/stylesheets/flat-ui-fonts.css">
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"> </script>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
      <%= yield(:head) %>
      <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-44399206-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
    <body class="<%= controller_name %> <%= action_name %>"></body>
      <div id="wrapper">
        <%= render 'layouts/messages' %>  
        <%= yield %>
      </div>
      <footer id="footer" class="footer hidden-print">
        <div class="container text-center">
          <div>
            Created by <a href="http://instagram.com/bradcink">Brad Cink</a>
          </div>
          <div id="footer-thanks">Many thanks to <a href="http://www.basicoh.com">Carlos Alvarez</a> for a fantastic theme.</div>
          <div id="footer-thanks">Please note, older versions of Internet Explorer may not be supported</div>
        </div>
</footer>
  </html>